### ISSUE TITLE
Setting secret key from env variable

### ISSUE THREAD

**Issue by sbaz44** [digitalfortress-tech/localstorage-slim#13] opened 2021-11-20 06:46 UTC
I am trying to set the secret key from environment variable but I cannot do that.

//  env
REACT_APP_LSKEY=123456789101112

//global setting
let key = Number(process.env.REACT_APP_LSKEY);  //converting string to number
ls.config.encrypt = true;
ls.config.secret = key;

NOTE: I tried using secret key as string, still same issue hence I converted it into NUMBER.

//setting data in local storage
 ls.set("foo", { bar: "baz" });
 
 //getting data from local storage
 let key = Number(process.env.REACT_APP_LSKEY);
let lsData= ls.get("foo", { secret: key });
console.log(lsData)  // o/p:     (empty)

![Screenshot_9](https://user-images.githubusercontent.com/37324431/142717387-5f9090e1-6d1b-4ecc-8737-bc694b29cb0a.png)

If I set  ls.config.secret = 50 then it is working fine but I want my secret key from env variable. Please help. Thank You.

**Comment by niketpathak** [comment] 2021-11-20 23:35
Hello, 

The default encryption implementation expects a number as its secret, so if you try using a string, it will certainly not work. Regarding your code, I was unable to reproduce the issue locally. I also created a [jsfiddle](https://jsfiddle.net/niketpathak/2aLg5pyt/) to demonstrate that it works just as expected. In your case, I suspect that the environment variable is not being passed correctly to localstorage-slim. As this is unrelated to localstorage-slim, I will go ahead and close this issue.

**Closed by niketpathak** 2021-11-20 23:35 UTC
